/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class proj_nativeinterface_test_HelloSpring */

#ifndef _Included_proj_nativeinterface_test_HelloSpring
#define _Included_proj_nativeinterface_test_HelloSpring
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     proj_nativeinterface_test_HelloSpring
 * Method:    print
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_proj_nativeinterface_test_HelloSpring_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
